### ISSUE TITLE
JSX in components

### ISSUE THREAD

**Issue by webondevices** [jacobp100/react-server-process#1]
Managed to run this successfully!
However, it would be great to introduce JSX to the mix as React.createElement is just not great when things get complicated. I tried many things with no luck unfortunately.

**Comment by jacobp100** [comment]
Thanks for the feedback! I used `createElement` so you can run it in native node. Added a comment to give the JSX equivalent.

**Comment by webondevices** [comment]
Thanks! I do know everything about the JSX syntax. But simply adding that JSX obviously breaks the script. Right now, without JSX, everything works without transpilation.

I'm interested how you would solve this problem. Right now I'm thinking about transpiling all the js files and JSX react component files with babel.

**Comment by jacobp100** [comment]
I usually just bundle my server files with webpack, but you can have a directory of transpired files. It's whatever works for you really!
